#!/usr/bin/env ruby

require_relative '../lib/init'

watermelons = Product.new('Watermelons', [ Bundle.new(3, 6.99), Bundle.new(5, 8.99) ])
pineapples = Product.new('Pineapples', [ Bundle.new(2, 9.95), Bundle.new(5, 16.95), Bundle.new(8, 24.95) ])
rockmelons = Product.new('Rockmelons', [ Bundle.new(3, 5.95), Bundle.new(5, 9.95), Bundle.new(9, 16.99) ])

shop = Shop.new([watermelons, pineapples, rockmelons])

# read order from file
order_lines = File.read('./orders.txt').split("\n")

order = shop.process_order(order_lines)

puts order.to_s